events {}
http {
    include /etc/nginx/mime.types;
    log_format lab '$remote_addr - $remote_user [$time_local] '
    '"$request" $status $body_bytes_sent '
    '"$http_referer" "$http_user_agent"';
    access_log /var/log/nginx/access_lab.log lab;
    error_log /var/log/nginx/error_lab.log warn;
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
    }
}